package org.klojang.jdbc;

import org.klojang.check.Check;
import org.klojang.invoke.Setter;
import org.klojang.invoke.SetterFactory;
import org.klojang.jdbc.x.JDBC;
import org.klojang.jdbc.x.sql.AbstractSQLSession;
import org.klojang.jdbc.x.sql.SQLInfo;
import org.klojang.util.ModulePrivate;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Map;

import static java.sql.Statement.NO_GENERATED_KEYS;
import static java.sql.Statement.RETURN_GENERATED_KEYS;
import static org.klojang.check.CommonChecks.*;
import static org.klojang.check.CommonExceptions.STATE;
import static org.klojang.convert.NumberMethods.convert;
import static org.klojang.invoke.NoSuchPropertyException.noSuchProperty;
import static org.klojang.util.ClassMethods.box;

/**
 * Facilitates the execution of SQL INSERT statements.
 */
public final class SQLInsert extends SQLStatement<SQLInsert> {

  @SuppressWarnings("unused")
  private static final Logger LOG = LoggerFactory.getLogger(SQLInsert.class);
  private static final String NO_KEYS_GENERATED = "no keys were generated";
  private static final String MULTIPLE_AUTO_KEYS = "multiple auto-increment keys not supported";
  private static final String DIRTY_INSTANCE = "insertAll() not allowed on dirty instance; call reset() first";

  private final List<String> keys = new ArrayList<>(5);

  private PreparedStatement ps;
  private boolean generateKeys;

  /**
   * For internal use only.
   */
  @ModulePrivate
  public SQLInsert(Connection con, AbstractSQLSession sql, SQLInfo sqlInfo) {
    super(con, sql, sqlInfo);
    this.ps = JDBC.getPreparedStatement(con, sqlInfo);
  }

  /**
   * Binds the values in the specified JavaBean to the parameters within the SQL
   * statement. Bean properties that do not correspond to named parameters will be
   * ignored. The effect of passing anything other than a proper JavaBean (e.g. an
   * {@code Integer}, {@code String} or array) is undefined.
   *
   * @param bean The bean whose values to bind to the named parameters within the SQL
   *     statement
   * @return this {@code SQLInsert} instance
   */
  @Override
  public SQLInsert bind(Object bean) {
    super.bind(bean);
    keys.add(null);
    return this;
  }

  /**
   * <p>Binds the values in the specified JavaBean to the parameters within the SQL
   * statement. Bean properties that do not correspond to named parameters will be
   * ignored. The effect of passing anything other than a proper JavaBean (e.g. an
   * {@code Integer}, {@code String} or array) is undefined. The {@code idProperty}
   * argument must be the name of the property corresponding to the primary key. The
   * generated value for that column will be bound back into the bean. Therefore, make
   * sure the bean is modifiable.
   *
   * <p><b><i>Klojang JDBC</i> does not support table definitions that generate keys for
   * multiple columns.</b>
   *
   * @param bean the bean whose values to bind to the named parameters within the SQL
   *     statement
   * @param idProperty the name of the property representing the auto-generated
   *     primary key.
   * @return this {@code SQLInsert} instance
   */
  public SQLInsert bind(Object bean, String idProperty) {
    super.bind(bean);
    keys.add(idProperty);
    return this;
  }

  /**
   * Binds the values in the specified map to the parameters within the SQL statement.
   * Keys that do not correspond to named parameters will be ignored.
   *
   * @param map the map whose values to bind to the named parameters within the SQL
   *     statement
   * @return this {@code SQLInsert} instance
   */
  @Override
  public SQLInsert bind(Map<String, Object> map) {
    super.bind(map);
    keys.add(null);
    return this;
  }

  /**
   * Binds the values in the specified map to the parameters within the SQL statement.
   * Keys that do not correspond to named parameters will be ignored. The {@code idKey}
   * argument must be the name of the map key corresponding to the table's primary key.
   * The generated value for that column will be bound back into the map. Therefore, make
   * sure the map is modifiable.
   *
   * <p><b><i>Klojang JDBC</i> does not support table definitions that generate keys for
   * multiple columns.</b>
   *
   * @param map the map whose values to bind to the named parameters within the SQL
   *     statement
   * @param idKey the name of the map key representing the auto-generated primary
   *     key.
   * @return this {@code SQLInsert} instance
   */
  public SQLInsert bind(Map<String, ?> map, String idKey) {
    super.bind(map);
    keys.add(idKey);
    return this;
  }

  /**
   * Executes the INSERT statement. If any JavaBean was bound while specifying its ID
   * property, the key generated by the database will be bound back into the JavaBean. The
   * same applies <i>mutatis mutandis</i> for {@code Map} objects.
   */
  @SuppressWarnings({"unchecked", "rawtypes"})
  public void execute() {
    boolean mustBindBack = keys.stream().anyMatch(notNull());
    try {
      if (!mustBindBack) {
        exec(false);
      } else {
        exec(true);
        try (ResultSet rs = ps.getGeneratedKeys()) {
          Check.that(rs.next()).is(yes(), NO_KEYS_GENERATED);
          Check.that(rs.getMetaData().getColumnCount()).is(eq(), 1, MULTIPLE_AUTO_KEYS);
          long id = rs.getLong(1);
          for (int i = 0; i < keys.size(); ++i) {
            String key = keys.get(i);
            if (key != null) {
              Object obj = bindings.get(i);
              if (obj instanceof Map map) {
                map.put(key, id);
              } else {
                setIdProperty(obj, key, id);
              }
            }
          }
        }
      }
    } catch (Throwable t) {
      throw KlojangSQLException.wrap(t, sqlInfo);
    } finally {
      reset();
    }
  }

  /**
   * Executes the INSERT statement and returns the key generated by the database. If the
   * database generated keys for multiple columns, a {@link KlojangSQLException} is
   * thrown, as this is not supported by <i>Klojang JDBC</i>.
   *
   * @return the key generated by the database
   */
  public long executeAndGetID() {
    try {
      exec(true);
      try (ResultSet rs = ps.getGeneratedKeys()) {
        Check.that(rs.next()).is(yes(),
            () -> new KlojangSQLException(NO_KEYS_GENERATED));
        Check.that(rs.getMetaData().getColumnCount()).is(eq(), 1,
            () -> new KlojangSQLException(MULTIPLE_AUTO_KEYS));
        return rs.getLong(1);
      }
    } catch (Throwable t) {
      throw KlojangSQLException.wrap(t, sqlInfo);
    } finally {
      reset();
    }
  }

  public <U> void insertBatch(Collection<U> beans) {
    Check.on(STATE, bindings).is(empty(), DIRTY_INSTANCE);
    try {
      for (U bean : beans) {
        bindings.clear();
        bindings.add(bean);
        exec(false);
      }
    } catch (Throwable t) {
      throw KlojangSQLException.wrap(t, sqlInfo);
    } finally {
      reset();
    }
  }

  @Override
  void initialize() {
    keys.clear();
    try {
      ps.clearParameters();
    } catch (SQLException e) {
      throw KlojangSQLException.wrap(e, sqlInfo);
    }
  }

  /**
   * Releases all resources held by this instance. You cannot reuse this instance after a
   * call to this method.
   */
  @Override
  public void close() {
    close(ps);
  }

  private void exec(boolean generateKeys) throws Throwable {
    int x = generateKeys ? RETURN_GENERATED_KEYS : NO_GENERATED_KEYS;
    if (ps == null) {
      ps = con.prepareStatement(sqlInfo.jdbcSQL(), x);
    } else if (this.generateKeys != generateKeys) {
      ps.close();
      ps = con.prepareStatement(sqlInfo.jdbcSQL(), x);
    }
    this.generateKeys = generateKeys;
    applyBindings(ps);
    ps.executeUpdate();
  }

  private static void setIdProperty(Object bean, String idProperty, long value)
      throws Throwable {
    SetterFactory sf = SetterFactory.INSTANCE;
    Map<String, Setter> setters = sf.getSetters(bean.getClass());
    Check.that(idProperty).is(keyIn(), setters, () -> noSuchProperty(bean, idProperty));
    Setter setter = setters.get(idProperty);
    // make sure we're OK if the ID property is not a long
    Number id = convert(value, (Class) box(setter.getParamType()));
    setter.write(bean, id);
  }

}
